baseURL: "https://github.amboss-zustellung.space/"
languageCode: "en-us"
title: "Amboss-incoming"
theme: "hugo-theme-bootstrap"
enableGitInfo: true


buildDrafts: true
buildExpired: false
buildFuture: false



menu:
  main:
    - identifier: "root"
      name: "Home"
      url: "/"
      weight: 10
      pre: "fas fa-home"
    - identifier: "posts"
      name: "Posts"
      url: "/posts/"
      weight: 20
      pre: "fas fa-list"
    - identifier: "blog"
      name: "Blog"
      url: "/tags/blog/"
      weight: 20
      pre: '<i class="fab fa-fw fa-rss"></i>'
    - identifier: "categories"
      name: "Categories"
      url: "/categories"
      weight: 20
      pre: '<i class="fab fa-fw fa-rss"></i>'
      parent: "posts"
    - identifier: "tags"
      name: "Tags"
      url: "/tags"
      weight: 20
      pre: '<i class="fab fa-fw fa-rss"></i>'
      parent: "posts"

    - identifier: "about"
      name: "About"
      url: "/about/"
      weight: 100
      pre: "fas fa-info fa-fw"
    - identifier: "contact"
      name: "Contact"
      url: "/contact/"
      weight: 100
#      pre: "fas fa-info fa-fw"
      parent: "about"


    - name: "Github"
      url: "https://github.com/jwalzer/github.amboss-zustellung.de"
      pre: '<i class="fab fa-fw fa-github"></i>'

taxonomies:
  category: "categories"
  tag: "tags"


summaryLength: 250 # default 70

social:
  email: "info@amboss-zustellung.space"
  github: "jwalzer"
  twitter: "janwalzer"


params:
  AuthorName: Jan Walzer
  GitHubUser: jwalzer
  SidebarRecentLimit: 5
  twitter: janwalzer
  github: jwalzer
  hideMeta: false
  footerContactButton: "contact/index.md"

  # used in layouts/partials/footer.bottom.html
  bottomLeft: ""
  bottomRight: 'created with [Hugo](https://gohugo.io) '

  traceFlags: "html-comment:debug-shortcodes"
  jumbotrons:
    # used in layouts/partials/front.jumbotrons.carousel.html
    # enable or disable jumbotrons on frontpage
    # see some examples in 'exampleSite/data/jumbotron'
    enable: true
  features:
    # used in layouts/partials/front.features.html
    # enable or disable features on frontpage
    # see some examples in 'exampleSite/data/features'
    enable: true
    animate: false
  options:
    # used in layouts/partials/page.nav.breadcrump.html
    showNavBreadcrump: true
    navBreadcrumpTitle: true
    navBreadcrumpHome: true
  anchor:
    # layouts/_default/baseof.html
    enable: true
    icon: "fas fa-anchor"
    #icon: "fas fa-link"
  theme:
    bootstrapTheme: 'solar'
    backgroundColor: "#D0D0C0"
    header:
      fontColor: "#101080"
      linkColor: "#101080"
      backgroundColor: "#C0C0B0"
    footer:
      fontColor: "#101080"
      linkColor: "#101080"
      backgroundColor: "#C0C0B0"
      democolumn:
        - text: "text1"
        - text: "text3"
  recentPosts:
    footerNumOfPosts: 5
    enableFooter: true
    title: "Recent-Title-Here"
  blog:
    title: "Blog"
    icon: "fas fa-rss"

  fonts:
    body: "Open Sans"
  sidebar:
    enabled: true
    style: "right"
    democolumn:
      - title: "Foo"
        text: "bar"
      - title: "Foo"
        text: "bar"
      - title: "Foo"
        text: "bar"


frontmatter:
  date:
  - date
  - publishDate
  - lastmod
  expiryDate:
  - expiryDate
  lastmod:
  - ":git"
  - lastmod
  - date
  - publishDate
  publishDate:
  - publishDate
  - date

permalinks: /blog/:year/:month/:filename/

sitemap:
  changefreq: "monthly"
  priority: 0.5
  filename: "sitemap.xml"

markup:
  asciidocExt:
    attributes: {}
    backend: html5
    extensions: []
    failureLevel: fatal
    noHeaderOrFooter: true
    preserveTOC: false
    safeMode: unsafe
    sectionNumbers: false
    trace: false
    verbose: false
    workingFolderCurrent: false
  blackFriday:
    angledQuotes: true
    extensions: null
    extensionsMask: null
    footnoteAnchorPrefix: ""
    footnoteReturnLinkContents: ""
    fractions: true
    hrefTargetBlank: false
    latexDashes: true
    nofollowLinks: false
    noreferrerLinks: false
    plainIDAnchors: true
    skipHTML: false
    smartDashes: true
    smartypants: true
    smartypantsQuotesNBSP: false
    taskLists: true
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: false
      xhtml: false
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2

