baseURL: "https://github.amboss-zustellung.space/"
languageCode: "en-us"
title: "Amboss-incoming"
theme: "ananke"
enableGitInfo: true

params:
  - AuthorName: Jan Walzer
  - GitHubUser: jwalzer
  - SidebarRecentLimit: 5

frontmatter:
  date:
  - date
  - publishDate
  - lastmod
  expiryDate:
  - expiryDate
  lastmod:
  - ":git"
  - lastmod
  - date
  - publishDate
  publishDate:
  - publishDate
  - date

permalinks: /archive/:year/:month/:title/